### ISSUE TITLE
No duplication of information between README and files

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/template_AMU7T#3]
Commit: https://github.com/spinalcordtoolbox/template_AMU7T/commit/28dbe1974f5cd066440697edbaff57002182c5ac

the README shows this:

![image](https://github.com/spinalcordtoolbox/template_AMU7T/assets/2482071/1be273d3-65c8-403f-8c2a-1370cc85448e)

Which is taken from https://github.com/spinalcordtoolbox/template_AMU7T/blob/main/atlas/info_label.txt

problem: if one day https://github.com/spinalcordtoolbox/template_AMU7T/blob/main/atlas/info_label.txt changes, we will have to also change the README, and by experience I know that it will lead to human errors.

I'd rather remove any possible duplication (eg: you could display the content of a file, instead of duplicating out-of-sync its content)

@joshuacwnewton can you please help

**Comment by joshuacwnewton** [comment]
> I'd rather remove any possible duplication (eg: you could display the content of a file, instead of duplicating out-of-sync its content)

"Include directives" (i.e. displaying the contents of one file in another) occur mainly with the [RST file format](https://docutils.sourceforge.io/docs/ref/rst/directives.html#including-an-external-document-fragment) used by Sphinx documentation. (This is what we use on the [`pam50.rst`](https://spinalcordtoolbox.com/overview/concepts/pam50.html) page of the spinalcordtoolbox.com documentation, where we directly include the contents of the PAM50 `info_label.txt` files.)

However, sadly this "include" behavior has been disabled on GitHub due to security reasons:

- https://github.com/github/markup/issues/172
- https://github.com/github/markup/issues/346

So I'm not sure if there's much we can do to avoid de-duplication besides not including a list at all (and directly linking to `info_label.txt` instead.

**Comment by jcohenadad** [comment]
Right, that's what I feared. Well, let's keep the out-of-sync list then, and make sure it is always up-to-date
